### ISSUE TITLE
latest.yml hash for .exe release does not match

### ISSUE THREAD

**Issue by v4k0nd** [szTheory/exifcleaner#119]
I noticed that hash does not match for the .exe file. I few days back I noticed another project had the same issue, and they generated the latest.yaml files via Electron Builder. Could you check if it's just on my machine or does it really not match.
I checked two ways on my win machine:

`powershell> Get-FileHash .\ExifCleaner-Setup-3.4.0.exe -Algorithm SHA512`

`cmd> certutil -hashfile ExifCleaner-Setup-3.4.0.exe SHA512`

EDIT: accidentally pasted the commands for the other project that had this problem

**Comment by szTheory** [comment]
Thanks for the report! I just ran the sha 512 checksum for the Mac .dmg and it didn't match the release either. 

```bash
$ shasum -a 512 ExifCleaner-3.4.0.dmg 
d48c15121c24100a4b63dcadfc32b1b9ba38ddf0a0c5e095550a261e0372ef78f655ff6cae1e772bf32d5c68a0cfa44ce831ad1cb5bce7c0e9c9cef861ad89fb
```

Whereas `latest-mac.yml` from the releases page has the following

```yaml
version: 3.4.0
files:
  - url: ExifCleaner-3.4.0-mac.zip
    sha512: vCV4kCC9Wa/R+Veq/I9reo2IK1zZ92zvVKzteXOlj+sClxg9DHtj3E8y873pHWGpgC4xmhVfEjfQD5CYtAtdmg==
    size: 77893769
    blockMapSize: 82892
  - url: ExifCleaner-3.4.0.dmg
    sha512: 1IwVEhwkEApLY9yt/DKxubo43fCgxeCVVQomHgNy73j2Vf9srh53K/MtXGigz6RM6DGtHLW858Dpyc74Ya2J+w==
    size: 80393100
path: ExifCleaner-3.4.0-mac.zip
sha512: vCV4kCC9Wa/R+Veq/I9reo2IK1zZ92zvVKzteXOlj+sClxg9DHtj3E8y873pHWGpgC4xmhVfEjfQD5CYtAtdmg==
releaseDate: '2020-10-19T00:09:01.169Z'
```

I'm not sure what the issue is. Could be Electron Builder like you mentioned. I don't have a CI process in place I just run the cross-platform build on a Mac with the `yarn run publish` command from `package.json` which is an alias for this `yarn run compile && electron-builder --macos --linux --windows -p always` which compiles the webpack then builds the cross-platform targets and publishes to Github. 

I don't have a lot of time right now to dig into Electron Build problems but if someone can reproduce and open up an issue on the [electron-builder Github](https://github.com/electron-userland/electron-builder) or find others who are experiencing the same issues and report back that will really help. In the meantime if possible you could run ExifCleaner locally by [following the instructions here](https://github.com/sztheory/exifcleaner#run-the-app-in-dev-mode) for peace of mind.

Meanwhile I'm going to pin this issue to raise awareness and hopefully work toward a resolution using the wisdom of the crowd.
